# Generated by Django 2.2.1 on 2019-05-10 19:41

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents', validators=[posts.models.validate_file_extension], verbose_name='Файл'),
        ),
    ]
