# Generated by Django 2.2.1 on 2019-05-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='student_group',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('ПИ', 'Пилот'), ('ПО', 'Зритель'), ('ПА', 'Партнер')], default='ПО', max_length=2, verbose_name='Роль пользователя'),
        ),
    ]
