# Generated by Django 2.2.1 on 2019-05-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190505_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('ПИ', 'Пилот'), ('УЧ', 'Член команды'), ('ПА', 'Партнер'), ('ПО', 'Зритель')], default='ПО', max_length=2, verbose_name='Роль пользователя'),
        ),
    ]
