# Generated by Django 2.2.1 on 2019-05-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
