# Generated by Django 2.2.1 on 2019-05-22 20:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20190522_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 20, 24, 16, 152924, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
