# Generated by Django 2.2.1 on 2019-05-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_auto_20190522_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='url',
            field=models.CharField(default='123321', max_length=255, verbose_name='Адрес'),
        ),
    ]
