# Generated by Django 2.2.1 on 2019-05-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190511_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_engine',
            field=models.CharField(default='Нет данных', max_length=30, verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_power',
            field=models.CharField(default='Нет данных', max_length=30, verbose_name='Мощность в л.с.'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_tyres',
            field=models.CharField(default='Нет данных', max_length=30, verbose_name='Покрышки'),
        ),
    ]
